### PR TITLE
fix: update tab set value

### LINKED ISSUE #714: bug: Can't update editor's value via the updateTab method
### Describe the bug

I have a modal to input some important informations, and then it'll generate a string from these informations, and after i close this modal, the string should type into the editor.
```jsx
function() {
const handleSubmit = () => {
    molecule.editor.updateTab({
        id: current.tab.id,
       // update the editor's value by str
       data: Object.assign(current.tab.data,{value: str})
    })
}
return(
    <Modal onSubmit={handleSubmit}>
    ...
    </Modal>
)
}
```

### Versions

-   OS: MacOS
-   Browser: Chrome
-   Molecule: @0.9.0-beta.4.2

### Expected
- the editor's content replaced by the `str`

### Actually happening
- there is no changes in editor's content

### PR DESCRIPTION
**Pull request by Zaoei**
## Description

Can't update editor's value via the updateTab method

Fixes #714

## Changes

-   `editorInstance.onDidChangeModelContent` added comparisons are made through URIs to limit changes to different editors。This is because when you change the contents of the editor with setValue, the onDidChangeModelContent event is triggered, and leaving it unchecked will cause the updateTab method to be called in onDidChangeModelContent, causing a circular call
-   In the updateTab method, check if tab.data.value exists, and call setGroupEditorValue to update the editor text

## How Has This Been Tested?

-   [ ] use updateTab method
```
const handleSubmit = () => {
    molecule.editor.updateTab({
        id: current.tab.id,
       // update the editor's value by str
       data: Object.assign(current.tab.data,{value: str})
    })
}
```
-   [ ] View changes in editor text content

## Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings
-   [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: src/services/workbench/editorService.ts [hunk 1]
```diff
@@ -349,9 +359,20 @@ export class EditorService
                 groups,
             });
         }
+
         return updatedTab;
     }
 
+    public setGroupEditorValue(group: IEditorGroup, value: string) {
+        const modal = group.editorInstance?.getModel();
+        if (!modal) return;
```
Comment (mumiao) [inline src/services/workbench/editorService.ts:368]:
```suggestion
        if (!model) return;
```

Comment (Zaoei) [reply src/services/workbench/editorService.ts]: +1

**Comment by mumiao** [comment]
+1
